# -*- coding: utf-8 -*-
"""QAISU MODEL 1 - PYTHON CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G429Hwi2QfXO867ptjpfH3rmkKKeDgLq
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
import pulp
import os
import datetime
from dateutil.relativedelta import relativedelta
import psycopg2

file_path = 'Random_Sentetik3.xlsx'

def load_and_preprocess_data():

    # 1. UDF VERİSİ (Üretim Hattı Uygunsuzluk - Sentetik Veri 1)
    udf_cols = ['UDF_NO', 'KALEM', 'IS_EMRI', 'KSYM_SORUMLUSU_KARAR', 'KSYM_KOK_NEDEN',
                'HATA_TURU', 'HATA_SINIFI', 'MUAYENE_EDEN', 'ALIKONULAN_MIKTAR', 'YARATILMA_TARIHI']
    df_udf = pd.read_excel(file_path, sheet_name='Sentetik Veri 1', usecols=udf_cols)

    df_udf['KSYM_SORUMLUSU_KARAR'] = df_udf['KSYM_SORUMLUSU_KARAR'].fillna('Belirsiz')
    df_udf['KSYM_KOK_NEDEN'] = df_udf['KSYM_KOK_NEDEN'].fillna('Bilinmiyor')

    # 2. ÜRETİM VE İSKO VERİSİ (Sentetik Veri 2)
    isko_cols = ['IS_EMRI', 'STOK_KODU', 'IS_EMRI_BASLANGIC_MIKTARI',
                 'NIHAI_KABUL_MIKTARI', 'TAMAMLANMA_TARIHI']
    df_isko = pd.read_excel(file_path, sheet_name='Sentetik Veri 2', usecols=isko_cols)

    # İSKO (İlk Seferde Kalite Oranı) Hesabı
    df_isko['ISKO_ORANI'] = df_isko['NIHAI_KABUL_MIKTARI'] / df_isko['IS_EMRI_BASLANGIC_MIKTARI'].replace(0, np.nan)

    # 3. VIR VERİSİ (Tedarikçi Sapma Talepleri - Sentetik Veri 3)
    vir_cols = ['Numara', 'Stok Kodu', 'Nihai Karar', 'Kök Neden  Kodu', 'Tedarikçi', 'Sapma Sınıfı']
    df_vir = pd.read_excel(file_path, sheet_name='Sentetik Veri3', usecols=vir_cols)

    # İsim standartlaştırma (UDF'teki 'KALEM' ile VIR'daki 'Stok Kodu' eşleşecek)
    df_vir.rename(columns={'Stok Kodu': 'KALEM', 'Kök Neden  Kodu': 'VIR_KOK_NEDEN', 'Nihai Karar': 'VIR_KARAR'}, inplace=True)
    df_isko.rename(columns={'STOK_KODU': 'KALEM'}, inplace=True)

    return df_udf, df_isko, df_vir

def perform_eda(df_udf, df_isko, df_vir):

    print(f"\nUDF Veri Boyutu: {df_udf.shape}")
    print("UDF Karar Dağılımı:")
    print(df_udf['KSYM_SORUMLUSU_KARAR'].value_counts(normalize=True).head())

    print(f"\nVIR Veri Boyutu: {df_vir.shape}")
    print("VIR Karar Dağılımı:")
    print(df_vir['VIR_KARAR'].value_counts(normalize=True).head())

    ortak_kalemler = set(df_udf['KALEM']).intersection(set(df_vir['KALEM']))
    print(f"\nHem UDF'te hem VIR'da ortak bulunan Stok Kodu (Kalem) sayısı: {len(ortak_kalemler)}")

def feature_engineering_and_anomaly(df_udf, df_isko, df_vir):

    # 1. TİP DÜZELTMESİ
    len_udf = df_udf['KALEM'].astype(str).str.strip().str.len().max()
    len_isko = df_isko['KALEM'].astype(str).str.strip().str.len().max()
    len_vir = df_vir['KALEM'].astype(str).str.strip().str.len().max()

    dinamik_zfill = max(len_udf, len_isko, len_vir)

    df_isko['KALEM'] = df_isko['KALEM'].astype(str).str.strip().str.zfill(dinamik_zfill)
    df_udf['KALEM'] = df_udf['KALEM'].astype(str).str.strip().str.zfill(dinamik_zfill)
    df_vir['KALEM'] = df_vir['KALEM'].astype(str).str.strip().str.zfill(dinamik_zfill)

    # 2. İSKO Oranlarının UDF'e aktarılması (KALEM bazında ortalama İSKO)
    isko_avg = df_isko.groupby('IS_EMRI')['ISKO_ORANI'].mean().reset_index()
    df_udf = df_udf.merge(isko_avg, on='IS_EMRI', how='left')

    df_udf['ISKO_ORANI'] = df_udf['ISKO_ORANI'].fillna(df_udf['ISKO_ORANI'].mean())

    # 3. UDF İÇİN ANOMALİ SKORLAMASI (Isolation Forest)
    df_udf['HATA_TURU_FREQ'] = df_udf.groupby('HATA_TURU')['HATA_TURU'].transform('count')
    df_udf['HATA_SINIFI_FREQ'] = df_udf.groupby('HATA_SINIFI')['HATA_SINIFI'].transform('count')

    features_udf = ['ALIKONULAN_MIKTAR', 'ISKO_ORANI', 'HATA_TURU_FREQ', 'HATA_SINIFI_FREQ']
    X_udf = df_udf[features_udf].fillna(0)

    # Isolation Forest Modeli (contamination: anomalilerin tahmini oranı)
    dinamik_contamination_udf = 0.10
    print(f"Veriden türetilen UDF Anomali Oranı: {dinamik_contamination_udf:.3f}")
    iso_forest_udf = IsolationForest(n_estimators=100, contamination=dinamik_contamination_udf, random_state=42)
    iso_forest_udf.fit(X_udf)

    # Sklearn'de Decision Function negatif skorlar anomaliyi ifade eder.
    scores_udf = iso_forest_udf.decision_function(X_udf)
    scores_inverted_udf = (scores_udf.max() - scores_udf).reshape(-1, 1)

    scaler = MinMaxScaler()
    df_udf['A_i_Anomali_Skoru'] = scaler.fit_transform(scores_inverted_udf)

    # 4. VIR İÇİN ANOMALİ SKORLAMASI
    dinamik_contamination_vir = 0.10
    print(f"Veriden türetilen VIR Anomali Oranı: {dinamik_contamination_vir:.3f}")

    df_vir['TEDARIKCI_FREQ'] = df_vir.groupby('Tedarikçi')['Tedarikçi'].transform('count')
    df_vir['SAPMA_FREQ'] = df_vir.groupby('Sapma Sınıfı')['Sapma Sınıfı'].transform('count')

    X_vir = df_vir[['TEDARIKCI_FREQ', 'SAPMA_FREQ']].fillna(0)

    iso_forest_vir = IsolationForest(n_estimators=100, contamination=dinamik_contamination_vir, random_state=42)
    iso_forest_vir.fit(X_vir)

    scores_vir = iso_forest_vir.decision_function(X_vir)
    scores_inverted_vir = (scores_vir.max() - scores_vir).reshape(-1, 1)
    df_vir['A_i_Anomali_Skoru'] = scaler.fit_transform(scores_inverted_vir)

    return df_udf, df_vir

def train_ml_models_and_get_probabilities(df_udf, df_vir):

    # Hedef Değişkeni (KSYM_SORUMLUSU_KARAR) Sayısal Etiketlere Çevirme
    le_udf = LabelEncoder()
    df_udf['KARAR_ENCODED'] = le_udf.fit_transform(df_udf['KSYM_SORUMLUSU_KARAR'].astype(str))
    udf_classes = le_udf.classes_

    # Modelin Eğitileceği Özellikler
    features_udf = ['ALIKONULAN_MIKTAR', 'ISKO_ORANI', 'HATA_TURU_FREQ', 'HATA_SINIFI_FREQ', 'A_i_Anomali_Skoru']
    X_udf = df_udf[features_udf].fillna(0)
    y_udf = df_udf['KARAR_ENCODED']

    # Random Forest Sınıflandırıcı Eğitimi
    rf_udf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf_udf.fit(X_udf, y_udf)

    # Her kayıt için karar tiplerine ait Olasılıkları Tahmin Etme (P_{i,c})
    udf_probs = rf_udf.predict_proba(X_udf)

    # Olasılıkları UDF DataFrame'ine sütun olarak ekleme
    for i, class_name in enumerate(udf_classes):
        df_udf[f'P_c_{class_name}'] = udf_probs[:, i]

    # Hedef Değişkeni (VIR_KARAR / Nihai Karar) Sayısal Etiketlere Çevirme
    le_vir = LabelEncoder()
    df_vir['VIR_KARAR'] = df_vir['VIR_KARAR'].fillna('Belirsiz').astype(str)
    df_vir['KARAR_ENCODED'] = le_vir.fit_transform(df_vir['VIR_KARAR'])
    vir_classes = le_vir.classes_

    # Modelin Eğitileceği Özellikler
    features_vir = ['TEDARIKCI_FREQ', 'SAPMA_FREQ', 'A_i_Anomali_Skoru']
    X_vir = df_vir[features_vir].fillna(0)
    y_vir = df_vir['KARAR_ENCODED']

    # Random Forest Sınıflandırıcı Eğitimi
    rf_vir = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
    rf_vir.fit(X_vir, y_vir)

    vir_probs = rf_vir.predict_proba(X_vir)

    # Olasılıkları VIR DataFrame'ine sütun olarak ekleme
    for i, class_name in enumerate(vir_classes):
        df_vir[f'P_c_{class_name}'] = vir_probs[:, i]

    return df_udf, df_vir, udf_classes, vir_classes

def get_current_weights_from_db():
    # Veritabanına bağlanıp en son ayarı çekin
    # conn = psycopg2.connect(...)
    # cursor.execute("SELECT mode, w_cost, w_ml, w_risk, w_anomaly, w_supplier FROM system_settings ORDER BY updated_at DESC LIMIT 1")
    # row = cursor.fetchone()

    # Örnek Çıktı:
    row = {'mode': 'static', 'w_cost': 0.20, 'w_ml': 0.20, 'w_risk': 0.20, 'w_anomaly': 0.20, 'w_supplier': 0.20}

    return row

def update_dynamic_weights(feedback_df, current_weights, alpha=0.05):
    # current_weights = {'w1_cost': 0.2, 'w2_ml': 0.2, 'w3_risk': 0.2, 'w4_anomaly': 0.2, 'w5_supplier': 0.2}

    # 1. Mühendislerin sistemi ezme (override) davranışlarını analiz et
    # "Sistem Kabul Dedi, İnsan Hurda Yaptı" -> Risk ağırlığı artmalı
    risk_arttirici_mudahale = len(feedback_df[(feedback_df['AI_KARAR'] == 'Kabul') &
                                              (feedback_df['INSAN_KARAR'].isin(['Hurda', 'RET']))])

    # "Sistem Hurda Dedi, İnsan Kabul Yaptı" -> Maliyet ağırlığı artmalı (Risk azalmalı)
    maliyet_arttirici_mudahale = len(feedback_df[(feedback_df['AI_KARAR'].isin(['Hurda', 'RET'])) &
                                                 (feedback_df['INSAN_KARAR'] == 'Kabul')])

    toplam_islem = len(feedback_df)
    if toplam_islem == 0:
        return current_weights

    # 2. Değişim (Delta) hesaplama
    delta_risk = (risk_arttirici_mudahale / toplam_islem) - (maliyet_arttirici_mudahale / toplam_islem)
    delta_cost = -delta_risk # Maliyet ve risk ters orantılıdır

    # 3. Ağırlıkları güncelleme (alpha ile yumuşatarak)
    new_weights = current_weights.copy()
    new_weights['w_risk'] += alpha * delta_risk
    new_weights['w_anomaly'] += alpha * delta_risk * 0.5 # Anomali de riske paralel artar
    new_weights['w_cost'] += alpha * delta_cost

    # 4. Toplamın 1.0 ( %100 ) olmasını sağlama (Softmax veya MinMax Normalizasyonu)
    total_w = sum(new_weights.values())
    new_weights = {k: v / total_w for k, v in new_weights.items()}

    return new_weights

def run_optimization_model(df_udf, df_vir, udf_classes, vir_classes, df_isko, dinamik_w=None):

    # 1. Ağırlıkları Nereden Alacağımıza Karar Verelim
    if dinamik_w is not None:
        # Eğer dışarıdan bir ağırlık sözlüğü gönderilmişse (Simülasyon Modu)
        weights = dinamik_w
        calisma_modu = "SİMÜLASYON (DİNAMİK ÖĞRENME)"
    else:
        # Eğer parametre boşsa veritabanına bağlan (Canlı Ortam Modu)
        db_settings = get_current_weights_from_db()
        weights = db_settings
        calisma_modu = db_settings.get('mode', 'static').upper()

    # 2. Ağırlıkları Değişkenlere Ata
    w1 = weights.get('w_cost', 0.20)
    w2 = weights.get('w_ml', 0.20)
    w3 = weights.get('w_risk', 0.20)
    w4 = weights.get('w_anomaly', 0.20)
    w5 = weights.get('w_supplier', 0.20)

    print(f"Sistem şu anda {calisma_modu} modda çalışıyor.")
    print(f"Kullanılan Ağırlıklar -> Maliyet:{w1:.3f}, ML:{w2:.3f}, Risk:{w3:.3f}, Anomali:{w4:.3f}, Tedarikçi:{w5:.3f}")

    df_opt = df_udf.copy()
    df_vir_opt = df_vir.copy()

    # 1. PARAMETRELERİN HAZIRLANMASI (Data Mapping)

    # 1.A. UDF Parametreleri
    C_c = {'RU': 0.6, 'Hurda': 1.0, 'Kabul/OGK': 0.2, 'Islah': 0.5, 'RTV': 0.4}
    C_c = {c: C_c.get(c, 0.5) for c in udf_classes}

    vir_kalem_set = set(df_vir_opt['KALEM'])
    df_opt['VIR_KAYDI_VAR_MI'] = df_opt['KALEM'].apply(lambda x: 1 if x in vir_kalem_set else 0)

    vir_olan_risk = df_opt[df_opt['VIR_KAYDI_VAR_MI'] == 1]['KSYM_SORUMLUSU_KARAR'].isin(['Hurda', 'RET']).mean()
    vir_olmayan_risk = df_opt[df_opt['VIR_KAYDI_VAR_MI'] == 0]['KSYM_SORUMLUSU_KARAR'].isin(['Hurda', 'RET']).mean()

    if pd.isna(vir_olmayan_risk) or vir_olmayan_risk == 0:
        dinamik_m_cross = 1.1
    else:
        dinamik_m_cross = vir_olan_risk / vir_olmayan_risk

    dinamik_m_cross = max(1.0, min(3.0, dinamik_m_cross))
    print(f"\nVeriden türetilen M_cross (Çapraz Kayıt) Çarpanı: {dinamik_m_cross:.2f}x")

    df_opt['M_cross'] = df_opt['KALEM'].apply(lambda x: dinamik_m_cross if x in vir_kalem_set else 1.0)

    # UDF R_i (Kök Neden Risk Skoru)
    udf_riskli = ['Hurda', 'RTV', 'RU', 'Islah']
    udf_kok_riskleri = df_opt.groupby('KSYM_KOK_NEDEN')['KSYM_SORUMLUSU_KARAR'].apply(lambda x: x.isin(udf_riskli).mean()).to_dict()
    df_opt['R_i'] = df_opt['KSYM_KOK_NEDEN'].map(udf_kok_riskleri).fillna(0.3).clip(lower=0.1)

    # 1.B. VIR (Tedarikçi) Parametreleri
    vir_cost_mapping = {'Kabul': 0.1, 'RET': 1.0, 'RU': 0.6, 'Roketsan da değerlendirilecek': 0.3}
    C_c_vir = {c: vir_cost_mapping.get(c, 0.5) for c in vir_classes}

    # VIR R_j (Tedarikçi Kök Neden Risk Skoru)
    vir_riskli = ['RET', 'RU']
    vir_kok_riskleri = df_vir_opt.groupby('VIR_KOK_NEDEN')['VIR_KARAR'].apply(lambda x: x.isin(vir_riskli).mean()).to_dict()
    df_vir_opt['R_j'] = df_vir_opt['VIR_KOK_NEDEN'].map(vir_kok_riskleri).fillna(0.3).clip(lower=0.1)

    # 2. MODELİN KURULMASI VE KARAR DEĞİŞKENLERİ
    prob = pulp.LpProblem("Birlesik_Kalite_Karar_Optimizasyonu", pulp.LpMinimize)

    # x_i,c (UDF Karar Değişkenleri)
    x_udf = pulp.LpVariable.dicts("x_udf", ((i, c) for i in df_opt.index for c in udf_classes), cat='Binary')

    # x_j,c (VIR Karar Değişkenleri)
    x_vir = pulp.LpVariable.dicts("x_vir", ((j, c) for j in df_vir_opt.index for c in vir_classes), cat='Binary')

    # y_j (Etki-Tepki / Gelecek Etki Tahmin Değişkeni)
    y = pulp.LpVariable.dicts("y_j", (j for j in df_vir_opt.index), lowBound=0, upBound=1, cat='Continuous')

    # 3. KISITLAR (CONSTRAINTS)

    # Kısıt 1: Tek Karar Kısıtı
    for i in df_opt.index:
        prob += pulp.lpSum([x_udf[(i, c)] for c in udf_classes]) == 1, f"Tek_Karar_UDF_{i}"

    for j in df_vir_opt.index:
        prob += pulp.lpSum([x_vir[(j, c)] for c in vir_classes]) == 1, f"Tek_Karar_VIR_{j}"

    # Kısıt 2: İSKO (Minimum %90) Kısıtı
    ilgili_is_emirleri = df_opt['IS_EMRI'].unique()
    toplam_baslangic = df_isko[df_isko['IS_EMRI'].isin(ilgili_is_emirleri)]['IS_EMRI_BASLANGIC_MIKTARI'].sum()
    if toplam_baslangic == 0: toplam_baslangic = df_opt['ALIKONULAN_MIKTAR'].sum() * 10

    max_fire = toplam_baslangic * 0.10
    fire_kararlari = [c for c in udf_classes if c in ['Hurda', 'RTV', 'RU']]
    df_opt['ALIKONULAN_MIKTAR'] = pd.to_numeric(df_opt['ALIKONULAN_MIKTAR'], errors='coerce').fillna(0)

    prob += pulp.lpSum([df_opt.loc[i, 'ALIKONULAN_MIKTAR'] * x_udf[(i, c)] for i in df_opt.index for c in fire_kararlari]) <= max_fire, "ISKO_Kisit"

    gecmis_is_yuku = df_opt['MUAYENE_EDEN'].value_counts().to_dict()

    dinamik_kapasite_sozlugu = {}
    for personel, adet in gecmis_is_yuku.items():
        # Minimum 5 iş ver, üstünü geçmiş performansının %20 fazlası olarak ayarla
        dinamik_kapasite_sozlugu[personel] = max(5, int(adet * 1.2) + 5)

    personeller = df_opt['MUAYENE_EDEN'].unique()

    for personel in personeller:
        personel_kayitlari = df_opt[df_opt['MUAYENE_EDEN'] == personel].index
        kisiye_ozel_kapasite = dinamik_kapasite_sozlugu.get(personel, 10) # Bulamazsa default 10

        # Personelin atandığı işlerin toplamı, kendi dinamik kapasitesini aşamaz
        prob += pulp.lpSum([x_udf[(i, c)] for i in personel_kayitlari for c in udf_classes]) <= kisiye_ozel_kapasite, f"Kapasite_{personel}"

    # Kısıt 3: Etki-Tepki Fonksiyonu (VIR -> UDF Transferi)
    kabul_benzeri_vir_kararlari = [c for c in vir_classes if c not in ['RET', 'RU']]
    for j in df_vir_opt.index:
        dinamik_risk_carpani = df_vir_opt.loc[j, 'R_j'] * df_vir_opt.loc[j, 'A_i_Anomali_Skoru']

        prob += y[j] == pulp.lpSum([x_vir[(j, c)] for c in kabul_benzeri_vir_kararlari]) * dinamik_risk_carpani, f"Etki_Tepki_yj_{j}"

    # Eğer ML bir parçaya > %40 Hurda diyorsa, o parçanın Kabul edilmesi yasaklanır.
    if 'P_c_Hurda' in df_opt.columns:
        for i in df_opt.index:
            if df_opt.loc[i, 'P_c_Hurda'] > 0.40:
                prob += x_udf[(i, 'Kabul/OGK')] == 0, f"Kirmizi_Cizgi_Kabul_Engeli_{i}"

    # 4. ÇOK AMAÇLI TOPLAMSAL FONKSİYON (Multi-Objective Additive)

    # Hangi kararların riski/anomaliyi fabrika içine taşıdığını tanımlıyoruz
    risk_tasiyan_kararlar = ['Kabul/OGK', 'Islah']
    vir_risk_tasiyanlar = ['Kabul', 'Roketsan da değerlendirilecek']

    # UDF için ağırlıkların kendi içinde 1'e tamamlanması (w5 hariç)
    w_sum_udf = w1 + w2 + w3 + w4
    w1_udf, w2_udf, w3_udf, w4_udf = w1/w_sum_udf, w2/w_sum_udf, w3/w_sum_udf, w4/w_sum_udf

    # VIR için ağırlıkların kendi içinde 1'e tamamlanması (Tümü dahil)
    w_sum_vir = w1 + w2 + w3 + w4 + w5
    w1_vir, w2_vir, w3_vir, w4_vir, w5_vir = w1/w_sum_vir, w2/w_sum_vir, w3/w_sum_vir, w4/w_sum_vir, w5/w_sum_vir

    # Şimdi PuLP Amaç Fonksiyonunu bu düzeltilmiş ağırlıklarla kuralım:
    Z_maliyet_udf = pulp.lpSum([C_c[c] * df_opt.loc[i, 'M_cross'] * x_udf[(i, c)] for i in df_opt.index for c in udf_classes])
    Z_maliyet_vir = pulp.lpSum([C_c_vir[c] * 1.0 * x_vir[(j, c)] for j in df_vir_opt.index for c in vir_classes])

    Z_ml_udf = pulp.lpSum([(1.0 - df_opt.loc[i, f'P_c_{c}']) * x_udf[(i, c)] for i in df_opt.index for c in udf_classes])
    Z_ml_vir = pulp.lpSum([(1.0 - df_vir_opt.loc[j, f'P_c_{c}']) * x_vir[(j, c)] for j in df_vir_opt.index for c in vir_classes])

    Z_risk_udf = pulp.lpSum([df_opt.loc[i, 'R_i'] * x_udf[(i, c)] for i in df_opt.index for c in udf_classes if c in risk_tasiyan_kararlar])
    Z_risk_vir = pulp.lpSum([df_vir_opt.loc[j, 'R_j'] * x_vir[(j, c)] for j in df_vir_opt.index for c in vir_classes if c in vir_risk_tasiyanlar])

    Z_anomali_udf = pulp.lpSum([df_opt.loc[i, 'A_i_Anomali_Skoru'] * x_udf[(i, c)] for i in df_opt.index for c in udf_classes if c in risk_tasiyan_kararlar])
    Z_anomali_vir = pulp.lpSum([df_vir_opt.loc[j, 'A_i_Anomali_Skoru'] * x_vir[(j, c)] for j in df_vir_opt.index for c in vir_classes if c in vir_risk_tasiyanlar])

    Z_tedarikci_etki = pulp.lpSum([y[j] for j in df_vir_opt.index])

    # Toplam Amaç Fonksiyonu (Dengelenmiş)
    prob += (w1_udf * Z_maliyet_udf + w2_udf * Z_ml_udf + w3_udf * Z_risk_udf + w4_udf * Z_anomali_udf) + \
            (w1_vir * Z_maliyet_vir + w2_vir * Z_ml_vir + w3_vir * Z_risk_vir + w4_vir * Z_anomali_vir + w5_vir * Z_tedarikci_etki), "Total_Objective"

    # 5. ÇÖZÜM VE SONUÇLARI YAZDIRMA
    prob.solve()
    durum_kodu = pulp.LpStatus[prob.status]
    print(f"Optimizasyon Çözüm Durumu: {durum_kodu}")

    # GÜVENLİK KONTROLÜ (FALLBACK MEKANİZMASI)
    if durum_kodu == 'Optimal':
        # Model başarılı çözüldü, optimizasyon kararlarını al
        df_opt['OPTIMIZE_EDILMIS_KARAR'] = [
            c for i in df_opt.index for c in udf_classes if pulp.value(x_udf[(i, c)]) == 1.0
        ]
        df_vir_opt['OPTIMIZE_EDILMIS_VIR_KARAR'] = [
            c for j in df_vir_opt.index for c in vir_classes if pulp.value(x_vir[(j, c)]) == 1.0
        ]
    else:
        # Model çözümsüz kaldı (Infeasible). Kodun çökmesini engellemek için ML'in en yüksek olasılıklı tahminiyle devam et.
        print("⚠️ DİKKAT: Kapasite kısıtları aşıldı (Infeasible). B Planı: Makine Öğrenmesi (RF) tahminleri doğrudan uygulanıyor.")

        # UDF için en yüksek olasılıklı sınıfı bul
        udf_prob_cols = [col for col in df_opt.columns if col.startswith('P_c_')]
        df_opt['OPTIMIZE_EDILMIS_KARAR'] = df_opt[udf_prob_cols].idxmax(axis=1).str.replace('P_c_', '')

        # VIR için en yüksek olasılıklı sınıfı bul
        vir_prob_cols = [col for col in df_vir_opt.columns if col.startswith('P_c_')]
        df_vir_opt['OPTIMIZE_EDILMIS_VIR_KARAR'] = df_vir_opt[vir_prob_cols].idxmax(axis=1).str.replace('P_c_', '')

    # KARAR GEREKÇELENDİRME (EXPLAINABLE AI) HESAPLAMALARI

    # 1. UDF (Üretim Hattı) Kayıtları İçin Gerekçelendirme (4 Feature)
    explain_data_udf = []
    for i in df_opt.index:
        c_star = df_opt.loc[i, 'OPTIMIZE_EDILMIS_KARAR']

        # Kararın sistemdeki ceza puanları hesaplanıyor
        v_cost = w1 * (C_c[c_star] * df_opt.loc[i, 'M_cross'])
        v_ml = w2 * (1.0 - df_opt.loc[i, f'P_c_{c_star}'])
        v_risk = w3 * df_opt.loc[i, 'R_i'] if c_star in risk_tasiyan_kararlar else 0.0
        v_anomali = w4 * df_opt.loc[i, 'A_i_Anomali_Skoru'] if c_star in risk_tasiyan_kararlar else 0.0

        total_v = v_cost + v_ml + v_risk + v_anomali
        if total_v == 0: total_v = 1e-9 # Sıfıra bölünme hatasını engellemek için

        explain_data_udf.append({
            'Etki_Maliyet_Pct': round((v_cost / total_v) * 100, 1),
            'Etki_ML_Pct': round((v_ml / total_v) * 100, 1),
            'Etki_Risk_Pct': round((v_risk / total_v) * 100, 1),
            'Etki_Anomali_Pct': round((v_anomali / total_v) * 100, 1)
        })

    # Hesaplanan yüzdeleri UDF tablosuna ekliyoruz
    df_explain_udf = pd.DataFrame(explain_data_udf, index=df_opt.index)
    df_opt = pd.concat([df_opt, df_explain_udf], axis=1)

    # 2. VIR (Tedarikçi) Kayıtları İçin Gerekçelendirme (5 Feature - pct_supplier dahil)
    explain_data_vir = []
    for j in df_vir_opt.index:
        c_star = df_vir_opt.loc[j, 'OPTIMIZE_EDILMIS_VIR_KARAR']

        v_cost = w1 * (C_c_vir[c_star] * 1.0)
        v_ml = w2 * (1.0 - df_vir_opt.loc[j, f'P_c_{c_star}'])
        v_risk = w3 * df_vir_opt.loc[j, 'R_j'] if c_star in vir_risk_tasiyanlar else 0.0
        v_anomali = w4 * df_vir_opt.loc[j, 'A_i_Anomali_Skoru'] if c_star in vir_risk_tasiyanlar else 0.0

        # pct_supplier BURADA devreye giriyor! PuLP'taki y_j değişkeninin değerini okuyoruz.
        v_supplier = w5 * pulp.value(y[j])

        total_v = v_cost + v_ml + v_risk + v_anomali + v_supplier
        if total_v == 0: total_v = 1e-9

        explain_data_vir.append({
            'Etki_Maliyet_Pct': round((v_cost / total_v) * 100, 1),
            'Etki_ML_Pct': round((v_ml / total_v) * 100, 1),
            'Etki_Risk_Pct': round((v_risk / total_v) * 100, 1),
            'Etki_Anomali_Pct': round((v_anomali / total_v) * 100, 1),
            'Etki_Tedarikci_Pct': round((v_supplier / total_v) * 100, 1) # Tedarikçi Etkisi eklendi
        })

    # Hesaplanan yüzdeleri VIR tablosuna ekliyoruz
    df_explain_vir = pd.DataFrame(explain_data_vir, index=df_vir_opt.index)
    df_vir_opt = pd.concat([df_vir_opt, df_explain_vir], axis=1)

    return df_opt, df_vir_opt, prob.status

def run_health_check(df_udf, df_isko, df_vir, df_opt, prob_status):
    print("\nSİSTEM SAĞLIK KONTROLÜ (HEALTH CHECK)")

    # 1. Ham Veri ve Eşleşme Kontrolü
    print("\n[1] Veri Birleştirme Kontrolleri:")
    isko_nan = df_udf['ISKO_ORANI'].isna().sum()
    print(f" -> UDF içindeki tanımsız İSKO Oranı sayısı: {isko_nan} " + ("✅" if isko_nan == 0 else "❌"))

    # 2. Makine Öğrenmesi (Anomali) Kontrolü
    print("\n[2] İzolasyon Ormanı (Anomali Skoru) Kontrolleri:")
    udf_anomali_nan = df_udf['A_i_Anomali_Skoru'].isna().sum()
    vir_anomali_nan = df_vir['A_i_Anomali_Skoru'].isna().sum()
    print(f" -> UDF'te hesaplanamayan Anomali Skoru: {udf_anomali_nan} " + ("✅" if udf_anomali_nan == 0 else "❌"))
    print(f" -> VIR'da hesaplanamayan Anomali Skoru: {vir_anomali_nan} " + ("✅" if vir_anomali_nan == 0 else "❌"))

    # 3. Makine Öğrenmesi (Sınıflandırma/Olasılık) Kontrolü
    print("\n[3] Random Forest (P_i,c) Kontrolleri:")
    prob_cols = [col for col in df_udf.columns if col.startswith('P_c_')]
    if prob_cols:
        prob_nan_total = df_udf[prob_cols].isna().sum().sum()
        print(f" -> P_i,c (Karar Olasılıkları) içindeki toplam NaN: {prob_nan_total} " + ("✅" if prob_nan_total == 0 else "❌"))
        # Olasılıkların toplamı 1 mi? (Satır bazlı kontrol)
        prob_sums = df_udf[prob_cols].sum(axis=1)
        hatali_olasilik = len(prob_sums[~np.isclose(prob_sums, 1.0)])
        print(f" -> Toplamı 1'e eşit olmayan olasılık satır sayısı: {hatali_olasilik} " + ("✅" if hatali_olasilik == 0 else "❌"))

    # 4. Yöneylem (OR) Optimizasyon Kontrolü
    print("\n[4] Yöneylem (OR) Modeli Kontrolleri:")
    durum_kodu = pulp.LpStatus[prob_status]
    if durum_kodu == "Optimal":
        print(f" -> Model Çözüm Durumu: {durum_kodu} ✅ (Matematiksel olarak en kusursuz karar seti bulundu)")
    elif durum_kodu == "Infeasible":
        print(f" -> Model Çözüm Durumu: {durum_kodu} ❌ (UYARI: Kısıtlarınız çakışıyor. Örneğin, kişi başına 50 kapasite sınırı koydunuz ama veri setinde 1 kişiye 150 iş yığılmış olabilir. Kapasite kısıtını gevşetmeniz gerekebilir.)")
    else:
        print(f" -> Model Çözüm Durumu: {durum_kodu} ⚠️")

    # 5. Nihai Karar Çıktısı Kontrolü
    print("\n[5] Nihai Çıktı (Superset Öncesi) Kontrolleri:")
    atanmamis_karar = df_opt['OPTIMIZE_EDILMIS_KARAR'].isna().sum()
    print(f" -> Optimizasyon motorunun karar veremediği (NaN) kayıt sayısı: {atanmamis_karar} " + ("✅" if atanmamis_karar == 0 else "❌"))

def export_for_superset(df_udf, df_vir):

    udf_prob_cols = [col for col in df_udf.columns if col.startswith('P_c_')]

    udf_export_cols = [
        'UDF_NO', 'YARATILMA_TARIHI', 'KALEM', 'IS_EMRI', 'KSYM_SORUMLUSU_KARAR', 'OPTIMIZE_EDILMIS_KARAR',
        'HATA_TURU', 'HATA_SINIFI', 'MUAYENE_EDEN', 'ALIKONULAN_MIKTAR',
        'ISKO_ORANI', 'Etki_Maliyet_Pct', 'Etki_ML_Pct', 'Etki_Risk_Pct', 'Etki_Anomali_Pct',
    ] + udf_prob_cols

    df_udf_export = df_udf[udf_export_cols].copy()

    df_udf_export['KARAR_UYUSMAZLIGI'] = df_udf_export.apply(
        lambda x: 'Uyuşmazlık Var' if str(x['KSYM_SORUMLUSU_KARAR']) != str(x['OPTIMIZE_EDILMIS_KARAR']) else 'Uyuşuyor',
        axis=1
    )

    vir_prob_cols = [col for col in df_vir.columns if col.startswith('P_c_')]

    vir_export_cols = [
        'Numara', 'KALEM', 'VIR_KARAR', 'OPTIMIZE_EDILMIS_VIR_KARAR', 'VIR_KOK_NEDEN', 'Tedarikçi',
        'Sapma Sınıfı', 'Etki_Maliyet_Pct', 'Etki_ML_Pct', 'Etki_Risk_Pct', 'Etki_Anomali_Pct', 'Etki_Tedarikci_Pct'
    ] + vir_prob_cols
    df_vir_export = df_vir[vir_export_cols].copy()

    df_vir_export['KARAR_UYUSMAZLIGI'] = df_vir_export.apply(
        lambda x: 'Uyuşmazlık Var' if str(x['VIR_KARAR']) != str(x['OPTIMIZE_EDILMIS_VIR_KARAR']) else 'Uyuşuyor', axis=1
    )

    udf_filename = 'superset_udf_karar_raporu.csv'
    vir_filename = 'superset_vir_risk_raporu.csv'

    df_udf_export.to_csv(udf_filename, index=False, encoding='utf-8-sig')
    df_vir_export.to_csv(vir_filename, index=False, encoding='utf-8-sig')

    print(f"\nSuperset dosyaları oluşturuldu:")
    print(f"1. {os.path.abspath(udf_filename)}")
    print(f"2. {os.path.abspath(vir_filename)}")

def evaluate_results(df_opt, df_vir_opt):
    print("\nSONUÇ DEĞERLENDİRME (UDF - ÜRETİM HATTI)")

    total_records = len(df_opt)
    eslesen = len(df_opt[df_opt['KSYM_SORUMLUSU_KARAR'].astype(str) == df_opt['OPTIMIZE_EDILMIS_KARAR'].astype(str)])
    uyusma_orani = (eslesen / total_records) * 100

    print(f"Toplam Değerlendirilen UDF Kaydı: {total_records}")
    print(f"Birebir Uyuşma: {eslesen} (%{uyusma_orani:.1f})\n")

    farkli_kararlar = df_opt[df_opt['KSYM_SORUMLUSU_KARAR'].astype(str) != df_opt['OPTIMIZE_EDILMIS_KARAR'].astype(str)]
    if not farkli_kararlar.empty:
        degisim_ozeti = farkli_kararlar.groupby(['KSYM_SORUMLUSU_KARAR', 'OPTIMIZE_EDILMIS_KARAR']).size().reset_index(name='Adet').sort_values(by='Adet', ascending=False)
        print(f"{'Geçmişteki İnsan Kararı':<25} | {'Sistemin Optimize Kararı':<25} | {'Adet'}")
        print("-" * 65)
        for _, row in degisim_ozeti.iterrows():
            print(f"{str(row['KSYM_SORUMLUSU_KARAR']):<25} | {str(row['OPTIMIZE_EDILMIS_KARAR']):<25} | {row['Adet']}")

    print("\nSONUÇ DEĞERLENDİRME (VIR - TEDARİKÇİ SAPMALARI)")

    total_vir = len(df_vir_opt)
    eslesen_vir = len(df_vir_opt[df_vir_opt['VIR_KARAR'].astype(str) == df_vir_opt['OPTIMIZE_EDILMIS_VIR_KARAR'].astype(str)])
    uyusma_vir = (eslesen_vir / total_vir) * 100

    print(f"Toplam Değerlendirilen VIR Kaydı: {total_vir}")
    print(f"Birebir Uyuşma: {eslesen_vir} (%{uyusma_vir:.1f})\n")

    farkli_vir = df_vir_opt[df_vir_opt['VIR_KARAR'].astype(str) != df_vir_opt['OPTIMIZE_EDILMIS_VIR_KARAR'].astype(str)]
    if not farkli_vir.empty:
        degisim_vir = farkli_vir.groupby(['VIR_KARAR', 'OPTIMIZE_EDILMIS_VIR_KARAR']).size().reset_index(name='Adet').sort_values(by='Adet', ascending=False)
        print(f"{'Geçmiş Tedarikçi Kararı':<25} | {'Sistemin Optimize Kararı':<25} | {'Adet'}")
        print("-" * 65)
        for _, row in degisim_vir.iterrows():
            print(f"{str(row['VIR_KARAR']):<25} | {str(row['OPTIMIZE_EDILMIS_VIR_KARAR']):<25} | {row['Adet']}")

class DecisionShiftSimulator:
    def __init__(self, months_to_simulate=6):
        self.months_to_simulate = months_to_simulate
        self.udf_forecast_data = []
        self.vir_forecast_data = []

    def run_simulation(self):
        print(f"\n--- BAŞLIYOR: Karar ve Tedarikçi Risk Bazlı {self.months_to_simulate} Aylık Projeksiyon ---")

        # 1. Mevcut Veriyi Yükle
        df_udf_hist, df_isko_hist, df_vir_hist = load_and_preprocess_data()
        df_udf_hist, df_vir_hist = feature_engineering_and_anomaly(df_udf_hist, df_isko_hist, df_vir_hist)
        df_udf_hist, df_vir_hist, udf_classes, vir_classes = train_ml_models_and_get_probabilities(df_udf_hist, df_vir_hist)

        # TEDARİKÇİ RİSK MOMENTUMU HESAPLAMA
        # Geçmiş performansı kötü olan tedarikçilerin her ay anomali skorlarını artırarak gelecekteki çöküşlerini simüle edeceğiz.
        supplier_stats = df_vir_hist.groupby('Tedarikçi').agg(
            Toplam_Islem=('Numara', 'count'),
            Kotu_Karar_Orani=('VIR_KARAR', lambda x: x.isin(['RET', 'RU']).mean()),
            Ort_Anomali=('A_i_Anomali_Skoru', 'mean')
        )

        # Risk Momentum: Kötü karar oranı ve anomalisi yüksek olanlar her ay %X daha kötüye gider
        supplier_stats['Aylik_Bozulma_Hizi'] = (supplier_stats['Kotu_Karar_Orani'] * 0.15) + (supplier_stats['Ort_Anomali'] * 0.05)

        avg_monthly_udf = len(df_udf_hist) // 3
        avg_monthly_vir = len(df_vir_hist) // 3

        current_date = datetime.date.today()
        aktif_agirliklar = {
            'w_cost': 0.20, 'w_ml': 0.20, 'w_risk': 0.20, 'w_anomaly': 0.20, 'w_supplier': 0.20
        }

        for month_offset in range(1, self.months_to_simulate + 1):
            sim_date = current_date + relativedelta(months=month_offset)
            month_label = sim_date.strftime("%Y-%m")
            print(f"\n>> Simüle Edilen Ay: {month_label} | Çözümleniyor...")

            df_udf_sim = df_udf_hist.sample(n=avg_monthly_udf, replace=True).copy()
            df_vir_sim = df_vir_hist.sample(n=avg_monthly_vir, replace=True).copy()
            df_udf_sim.reset_index(drop=True, inplace=True)
            df_vir_sim.reset_index(drop=True, inplace=True)

            # GELECEK TEDARİKÇİ BOZULMASINI (DEGRADATION) VERİYE ENJEKTE ETME
            # İlerleyen aylarda riskli tedarikçilerin anomali skorları sentetik olarak artırılır.
            for idx, row in df_vir_sim.iterrows():
                tedarikci = row['Tedarikçi']
                if tedarikci in supplier_stats.index:
                    bozulma_hizi = supplier_stats.loc[tedarikci, 'Aylik_Bozulma_Hizi']
                    # Bileşik bozulma formülü: Mevcut_Skor * (1 + Bozulma_Hızı)^Ay
                    yeni_anomali = row['A_i_Anomali_Skoru'] * ((1 + bozulma_hizi) ** month_offset)
                    # Skoru max 1.0 ile sınırla
                    df_vir_sim.at[idx, 'A_i_Anomali_Skoru'] = min(1.0, yeni_anomali)

            # Güncellenmiş risk verileriyle optimizasyonu çalıştır
            df_opt, df_vir_opt, prob_status = run_optimization_model(df_udf_sim, df_vir_sim, udf_classes, vir_classes,
                                                                     df_isko_hist, dinamik_w=aktif_agirliklar)

            feedback_df = pd.DataFrame({
                'AI_KARAR': df_opt['OPTIMIZE_EDILMIS_KARAR'],
                'INSAN_KARAR': df_opt['KSYM_SORUMLUSU_KARAR']
            })

            aktif_agirliklar = update_dynamic_weights(feedback_df, aktif_agirliklar, alpha=0.10)

            # Sonuçları Kaydet
            df_opt['Sim_Ay_Yil'] = month_label
            df_opt['Senaryo_Insan_Karari'] = df_opt['KSYM_SORUMLUSU_KARAR']
            df_opt['Senaryo_AI_Karari'] = df_opt['OPTIMIZE_EDILMIS_KARAR']
            df_opt['SIM_UDF_NO'] = [f"F-{month_label}-U{i}" for i in range(len(df_opt))]
            udf_cols = ['Sim_Ay_Yil', 'SIM_UDF_NO', 'KALEM', 'HATA_TURU', 'Senaryo_Insan_Karari', 'Senaryo_AI_Karari', 'Etki_Maliyet_Pct', 'Etki_ML_Pct', 'Etki_Risk_Pct', 'Etki_Anomali_Pct']
            self.udf_forecast_data.append(df_opt[udf_cols])

            df_vir_opt['Sim_Ay_Yil'] = month_label
            df_vir_opt['Senaryo_Insan_Karari'] = df_vir_opt['VIR_KARAR']
            df_vir_opt['Senaryo_AI_Karari'] = df_vir_opt['OPTIMIZE_EDILMIS_VIR_KARAR']
            df_vir_opt['SIM_VIR_NO'] = [f"F-{month_label}-V{i}" for i in range(len(df_vir_opt))]
            vir_cols = ['Sim_Ay_Yil', 'SIM_VIR_NO', 'KALEM', 'Tedarikçi', 'Sapma Sınıfı', 'Senaryo_Insan_Karari', 'Senaryo_AI_Karari', 'A_i_Anomali_Skoru', 'Etki_Maliyet_Pct', 'Etki_ML_Pct', 'Etki_Risk_Pct', 'Etki_Anomali_Pct', 'Etki_Tedarikci_Pct']
            self.vir_forecast_data.append(df_vir_opt[vir_cols])

        final_udf_forecast = pd.concat(self.udf_forecast_data, ignore_index=True)
        final_vir_forecast = pd.concat(self.vir_forecast_data, ignore_index=True)

        final_udf_forecast['Karar_Degisti_Mi'] = np.where(final_udf_forecast['Senaryo_Insan_Karari'] == final_udf_forecast['Senaryo_AI_Karari'], 'Hayır', 'Evet')

        final_udf_forecast.to_csv('superset_udf_karar_simulasyonu.csv', index=False)
        final_vir_forecast.to_csv('superset_vir_karar_simulasyonu.csv', index=False)

        print("\n✅ Karar Simülasyonu Tamamlandı! Detaylı CSV dosyaları Superset için hazır.")
        return final_udf_forecast, final_vir_forecast

if __name__ == "__main__":
    # 1. Veri Yükleme
    df_udf, df_isko, df_vir = load_and_preprocess_data()
    perform_eda(df_udf, df_isko, df_vir)

    # 2. Özellik Mühendisliği ve Anomali
    df_udf, df_vir = feature_engineering_and_anomaly(df_udf, df_isko, df_vir)

    # 3. ML Olasılıkları
    df_udf, df_vir, udf_classes, vir_classes = train_ml_models_and_get_probabilities(df_udf, df_vir)

    # 4. Optimizasyon (OR) Modeli
    df_udf_final, df_vir_final, prob_status = run_optimization_model(df_udf, df_vir, udf_classes, vir_classes, df_isko)

    run_health_check(df_udf, df_isko, df_vir_final, df_udf_final, prob_status)

    # 5. Sonuç Değerlendirme
    evaluate_results(df_udf_final, df_vir_final)

    # 6. Superset Export
    export_for_superset(df_udf_final, df_vir_final)

    # 7. Simülasyonu Başlat
    simulator = DecisionShiftSimulator(months_to_simulate=6)
    df_udf_f, df_vir_f = simulator.run_simulation()

    # Hızlı Konsol Özeti
    print("\n[HIZLI ÖZET] İnsan vs AI Karar Dağılımı (Önümüzdeki 6 Ay Toplamı):")
    ozet = df_udf_f.groupby(['Senaryo_Insan_Karari', 'Senaryo_AI_Karari']).size().reset_index(name='Adet')
    print(ozet.sort_values(by='Adet', ascending=False).to_string(index=False))

 # 8. GELECEK 6 AYLIK TEDARİKÇİ RİSK ANALİZİ RAPORU
    print("\nTEDARİKÇİ RİSK VE ÇÖKÜŞ ANALİZİ (ÖNÜMÜZDEKİ 6 AY)")

    # Sistemin RET veya RU kararı verdiği kayıtları filtreliyoruz
    ai_ret_kararlari = df_vir_f[df_vir_f['Senaryo_AI_Karari'].isin(['RET', 'RU'])]

    # Tedarikçi bazında gruplama yapıp gelecekte en çok red yiyecek firmaları buluyoruz
    tedarikci_gelecek_risk = ai_ret_kararlari.groupby('Tedarikçi').agg(
        Toplam_Red_Tahmini=('SIM_VIR_NO', 'count'),
        Ortalama_Gelecek_Anomali=('A_i_Anomali_Skoru', 'mean')
    ).reset_index()

    # Toplam işleme oranını hesaplayarak hacimden bağımsız "Red Yeme Olasılığı" buluyoruz
    toplam_islem = df_vir_f.groupby('Tedarikçi').size().reset_index(name='Gelecek_Islem_Hacmi')
    tedarikci_gelecek_risk = pd.merge(tedarikci_gelecek_risk, toplam_islem, on='Tedarikçi')
    tedarikci_gelecek_risk['Red_Yeme_Orani_%'] = (tedarikci_gelecek_risk['Toplam_Red_Tahmini'] / tedarikci_gelecek_risk['Gelecek_Islem_Hacmi']) * 100

    # Risk skoru bazında tüm tedarikçileri sırala
    tedarikci_gelecek_risk = tedarikci_gelecek_risk.sort_values(by=['Red_Yeme_Orani_%', 'Ortalama_Gelecek_Anomali'], ascending=[False, False])
    riskli_top_5 = tedarikci_gelecek_risk.head(5)

    print("Gelecek 6 Ay İçinde Tedarik Zincirini En Çok Tehdit Edecek 5 Tedarikçi:\n")
    print(f"{'Tedarikçi Adı':<25} | {'Tahmini Red İşlem':<20} | {'Red Yeme Oranı':<15} | {'Kritik Anomali Skoru'}")
    print("-" * 85)
    for _, row in riskli_top_5.iterrows():
        print(f"{str(row['Tedarikçi']):<25} | {row['Toplam_Red_Tahmini']:<8} (/{row['Gelecek_Islem_Hacmi']:<8}) | %{row['Red_Yeme_Orani_%']:<13.1f} | {row['Ortalama_Gelecek_Anomali']:.3f}")

    print("\nYORUM: Bu firmaların anomali skorları geçmiş kusurlarından dolayı her ay logaritmik olarak artırıldı.")
    print("Sistem, bu firmalardan gelecek parçalarda kapasite ve tolerans sınırlarını aşacağını öngörerek 'RET/RU' kararlarını maksimize etti.")
    print("Satın alma veya tedarikçi kalitesi ekiplerinin, kırmızı bayrak çeken bu firmalarla önleyici denetim yapması önerilir.")

    # Tedarikçi risk analizini CSV'ye kaydetme
    tedarikci_csv_adi = 'superset_tedarikci_risk_analizi.csv'
    tedarikci_gelecek_risk.to_csv(tedarikci_csv_adi, index=False, encoding='utf-8-sig')
    print(f"\n✅ Tüm tedarikçi risk analizi CSV olarak kaydedildi: {os.path.abspath(tedarikci_csv_adi)}")

    # 9. GELECEK 6 AYLIK KRİTİK PARÇA (KALEM) VE AKSİYON ANALİZİ
    print("\nKRİTİK PARÇA (KALEM) RİSK VE ÖNLEYİCİ AKSİYON ANALİZİ (ÖNÜMÜZDEKİ 6 AY)")

    # 1. UDF (Üretim) tarafında riskli parçaları bul (AI Kararı Hurda, RTV veya RU olanlar)
    udf_hurda = df_udf_f[df_udf_f['Senaryo_AI_Karari'].isin(['Hurda', 'RTV', 'RU'])]
    udf_parca_risk = udf_hurda.groupby('KALEM').size().reset_index(name='Uretim_Hata_Sayisi')

    # 2. VIR (Tedarik) tarafında riskli parçaları bul (AI Kararı RET veya RU olanlar)
    vir_ret = df_vir_f[df_vir_f['Senaryo_AI_Karari'].isin(['RET', 'RU'])]
    vir_parca_risk = vir_ret.groupby('KALEM').size().reset_index(name='Tedarik_Hata_Sayisi')

 # 3. İki risk tablosunu KALEM (Stok Kodu) bazında birleştir
    parca_risk = pd.merge(udf_parca_risk, vir_parca_risk, on='KALEM', how='outer').fillna(0)
    parca_risk['Toplam_Riskli_Islem'] = parca_risk['Uretim_Hata_Sayisi'] + parca_risk['Tedarik_Hata_Sayisi']

    # SADECE ANA TABLOYU OLUŞTURUYORUZ (Top 10'u şimdilik ayırmıyoruz)
    parca_risk_all = parca_risk[parca_risk['Toplam_Riskli_Islem'] > 0].sort_values(by='Toplam_Riskli_Islem', ascending=False).copy()

    # 4. Uzman Sistem: Kaynağa Göre Dinamik Aksiyon Atama Fonksiyonu
    def aksiyon_oner(row):
        u_hata = row['Uretim_Hata_Sayisi']
        t_hata = row['Tedarik_Hata_Sayisi']

        if t_hata > 0 and u_hata == 0:
            return "Sadece Tedarikçi: IQC (Giriş Kalite) muayenesini %100'e çekin. Tedarikçi sertifikalarını denetleyin."
        elif u_hata > 0 and t_hata == 0:
            return "Sadece Üretim: Hattaki makine/fikstür kalibrasyonunu kontrol edin. Operatör eğitimlerini yenileyin."
        elif t_hata > u_hata:
            return "Karma (Tedarik Ağırlıklı): Kötü hammadde hatta yansıyor. Tedarikçiye SCAR (Düzeltici Faaliyet) açın."
        elif u_hata > t_hata:
            return "Karma (Üretim Ağırlıklı): Tedarik sorunları var ama asıl zayiat üretimde. Proses parametrelerini (SOP) revize edin."
        else:
            return "Kronik/Tasarımsal Risk: Mühendislik ekibi teknik resim ve tolerans sınırlarını acilen gözden geçirmeli."

    # AKSİYONU SADECE ANA TABLOYA UYGULUYORUZ
    parca_risk_all['Onerilen_Aksiyon'] = parca_risk_all.apply(aksiyon_oner, axis=1)

    # HER ŞEY BİTTİKTEN SONRA TOP 10'U ALIYORUZ (Uyarıyı kökten çözen adım)
    parca_risk_top10 = parca_risk_all.head(10)

    # 5. Sonuçları Konsola Yazdır
    print(f"{'\nStok Kodu (KALEM)':<20} | {'Tedarik (VIR) Hata':<18} | {'Üretim (UDF) Hata':<18} | {'Sistemin Önleyici Aksiyon Önerisi'}")
    print("-" * 110)
    for _, row in parca_risk_top10.iterrows():
        print(f"{str(row['KALEM']):<20} | {int(row['Tedarik_Hata_Sayisi']):<18} | {int(row['Uretim_Hata_Sayisi']):<18} | {row['Onerilen_Aksiyon']}")

    # Kalem (Parça) risk analizini CSV'ye kaydetme
    kalem_csv_adi = 'superset_kalem_risk_ve_aksiyon_analizi.csv'
    parca_risk_all.to_csv(kalem_csv_adi, index=False, encoding='utf-8-sig')
    print(f"\n✅ Tüm kalem risk ve aksiyon analizi CSV olarak kaydedildi: {os.path.abspath(kalem_csv_adi)}")
